// Generated by CoffeeScript 1.7.1
(function() {
  var greet;

  greet = function(inputName, drinkMartinis) {
    if (drinkMartinis) {
      return 'Hello ' + inputName + ', you look so sexy today';
    } else {
      return "Hello " + inputName;
    }
  };

  module.exports = greet;

}).call(this);
